### ISSUE TITLE
Message buttons force logout sometimes

### ISSUE THREAD

**Issue by Rivenscryr** [mbin84ng4wopn8asn4m8nv4ha98n4tagn7mab/source#1]

**Comment by Rivenscryr** [comment]
How about adding delay between each click with setTimeout ?

**Comment by Rivenscryr** [comment]
I've added a delay (setTimeout)
Please test if it's still forcing logout

**Comment by Shole123** [comment]
Everything fine.

**Comment by Rivenscryr** [comment]
Logout issue still happens sometimes

**Comment by Shole123** [comment]
Nope, deleted 100 spy reports and nothing happen.

**Comment by Rivenscryr** [comment]
Do it more often
Get 1k spy reports and delete them

**Comment by Shole123** [comment]
No need for 1k spy reports, it deltes page by page. I tried many times nothing. We can increase delay to 150 but i think it is not needed. 
Everything fine with this for me.
