### ISSUE TITLE
Load resources buttons on Fleet 3 shifted

### ISSUE THREAD

**Issue by Rivenscryr** [mbin84ng4wopn8asn4m8nv4ha98n4tagn7mab/source#10]
![](http://i.imgur.com/05Ozjvh.png)

**Comment by Shole123** [comment]
http://prntscr.com/9rdmxa
Fine by me...

**Comment by Rivenscryr** [comment]
You have no commander :P

**Comment by Shole123** [comment]
No, it is just on attack mission.
http://prntscr.com/9rdnwp

**Comment by Shole123** [comment]
http://prntscr.com/9rdoah

**Comment by Rivenscryr** [comment]
you're right

**Comment by Shole123** [comment]
I would hide those buttons? Why would someone attack with resources hah

**Comment by Rivenscryr** [comment]
Fleetsaving on attack maybe

**Comment by Shole123** [comment]
Fixed in this commit
