### ISSUE TITLE
Press Enter in galaxy view when chatting does not send message

### ISSUE THREAD

**Issue by Rivenscryr** [mbin84ng4wopn8asn4m8nv4ha98n4tagn7mab/source#14]

**Comment by Rivenscryr** [comment]
Maybe disable keyboard shortcuts when chatting. Same problem with fleet pages

**Comment by Shole123** [comment]
Yep, i was thinking how to do that.

Maybe if chat window is open, keyboard shortcuts are disabled, but when he close chat window keyboard shortcuts will be active again.

**Comment by Rivenscryr** [comment]
Only disable when text field of chat is actually selected
