### ISSUE TITLE
Finish Spy Helper table

### ISSUE THREAD

**Issue by Rivenscryr** [mbin84ng4wopn8asn4m8nv4ha98n4tagn7mab/source#19]
To do:
-sorting
-adding action buttons for at least attacking and deleting
-marking messages will come in 6.0.2

**Comment by Shole123** [comment]
What about this two? 

!(http://s12.postimg.org/9bbm082fh/Screenshot.png)

**Comment by Rivenscryr** [comment]
What's with it?

**Comment by Shole123** [comment]
Adding check icon if attack is sent.
That count under table.
And
Button to link it to galaxy position.

That also for 6.0.1?

**Comment by Rivenscryr** [comment]
Let's do check for 6.0.2 maybe?
Do you know how to store data in AGO?
