### ISSUE TITLE
Mixed content 

### ISSUE THREAD

**Issue by Shole123** [mbin84ng4wopn8asn4m8nv4ha98n4tagn7mab/source#43]
Fleet page 1
http://prntscr.com/a9sd7x

Fleet page 2 
http://prntscr.com/a9sct1

Fleet page 3
http://prntscr.com/a9sd06

**Comment by Rivenscryr** [comment]
Those are images from CSS files
We need to set those to https

**Comment by Shole123** [comment]
Yeah, not big thing
