### ISSUE TITLE
Incompatibility with RaumDock - needs to be fixed for 6.2.0

### ISSUE THREAD

**Issue by Shole123** [mbin84ng4wopn8asn4m8nv4ha98n4tagn7mab/source#47]
![raumdock_ago](https://cloud.githubusercontent.com/assets/14963853/15098145/dd1431ec-1534-11e6-88dd-91a6da633ea8.png)

Techtree icon pushes text over buttons.
Button not working properly when AGO is turned on.
Calculations for building costs = can come later.

**Comment by Rivenscryr** [comment]
"Calculations for building costs = can come later."
already done, but not pushed yet

**Comment by Shole123** [comment]
Nice to know!
If you need anything poke me on IRC ^^

**Comment by Rivenscryr** [comment]
![](http://img.prntscr.com/img?url=http://i.imgur.com/GpDKnOg.png)

Hope this is ok

**Comment by Shole123** [comment]
Very nice! Good work
I will check tonight commits^^

**Comment by Shole123** [comment]
Works.

Just those two buttons don't work correctly for me because of the overlay.

![overlay](https://cloud.githubusercontent.com/assets/14963853/15175082/016a9cf2-1765-11e6-99fa-6f08d76e7818.png)

**Comment by Shole123** [comment]
![solution](https://cloud.githubusercontent.com/assets/14963853/15175158/63c74206-1765-11e6-96e2-a55db7d68de1.png)

solution

**Comment by Rivenscryr** [comment]
I need a wreckfield again
Attack me on 1:32:9 Planet please

**Comment by Shole123** [comment]
Fleet is on its way

**Comment by Rivenscryr** [comment]
should be fixed now
