### ISSUE TITLE
Csimulator

### ISSUE THREAD

**Issue by Rivenscryr** [mbin84ng4wopn8asn4m8nv4ha98n4tagn7mab/source#7]
Add button for TS, using API

![](http://i.imgur.com/uwITIoi.png)

**Comment by Rivenscryr** [comment]
We need a button for this
Can you ask vulca if she's willing to give us the template of the button she uses? Or if she wants to make a TrashSim button for us?

**Comment by Shole123** [comment]
Yep, i will ask him tomorrow :)

**Comment by Rivenscryr** [comment]
vulca is not female? lol

**Comment by Shole123** [comment]
This are icons from Warsaaalk 
First two for OGotcha, second two for TrashSim

![img] (http://s21.postimg.org/hanvbmjdf/action_buttons.png)


Java Script from Warsaaalk:
```javascript
var apiKey = /ogame-api:\/\/(sr\-[a-z]{2}\-\d{1,3}\-[0-9a-z]{40})/.exec(apiBtn.parentNode.href)[1];			
var apiCom = apiKey.split('-')[1], //Community
urlbase = c.config.trashsim.url;
if ("undefined" !== typeof c.config.trashsim.communities[apiCom]) {
urlbase += c.config.trashsim.communities[apiCom];
}
return urlbase + '?SR_KEY=' + apiKey + '#prefill=' + window.btoa(JSON.stringify(getSimulationBase(0)));
```

**Comment by Rivenscryr** [comment]
Great

**Comment by Rivenscryr** [comment]
What is that javascript ?

**Comment by Shole123** [comment]
building the trashsim URL and mapping the community to a trashsim language

**Comment by Rivenscryr** [comment]
Yeah but
apiBtn
c
are not defined? where is that snippet from?

**Comment by Shole123** [comment]
He sent me that in the morning, i can ask him for more

This is just a code which he uses, we can't use same, we don't have same variables.
I just wanted to show you, but sure as i said i can ask him for more.

**Comment by Rivenscryr** [comment]
Nah you don't need to ask him
I was just wondering. I'll write something for us

**Comment by Shole123** [comment]
Warsaalk will add Json file which contains available languages o TrashSim to his website

**Comment by Shole123** [comment]
https://trashsim.universeview.be/API/settings

**Comment by Rivenscryr** [comment]
Great!

**Comment by Shole123** [comment]
TS in other laguages for 6.0.2
